#!/usr/bin/python

import os
import os.path
import sys

import fritutils.termout

CONFIG_TEMPLATE="""#This is an autogenerated config file.
#It use the INI format.
#Create a section by evidence file that you have
"""

def initCommand():
    """
    Init command is used to create the .frit directory and a basic config file.
    if .frit/config already exists, it fails.
    """
    if os.path.exists('.frit/config'):
        fritutils.termout.printWarning("The '.frit/config file' already exists.")
    else:
        fritutils.termout.printSuccess("Creating '.frit/config'.")
        if not os.path.exists('.frit'):
            try:
                os.mkdir('.frit')
            except:
                fritutils.termout.printWarning("Cannot create .frit directory.")
                sys.exit(1)
        try:
            fc=open('.frit/config','w')
            fc.write(CONFIG_TEMPLATE)
            fc.close()
        except:
            fritutils.termout.printWarning("Cannot write .frit/config file.")
            sys.exit(1)

