#!/usr/bin/python

import os
import os.path
import sys

import fritutils.termout

CONFIG_TEMPLATE="""#This is an autogenerated config file.
#It use the INI format.
#Create a section by evidence file that you have
# example :
#[Evidence1]
#    Name=pc1.aff
#    Format=aff
#    [[Filesystem1]]
#        Format=NTFS
#        Offset=63*512
#        Sizelimit=1024*1024
[Extensions]
     Office = .odt .ods .odp .doc .docx .xls .xlsx .ppt .pptx .pdf
     Emails = .pst .ost .dbx .eml
     Databases = .mdb .sqlite
     Images = .jpg .jpeg .png .tif
"""

def initCommand():
    """
    Init command is used to create the .frit directory and a basic config file.
    if .frit/config already exists, it fails.
    """
    if os.path.exists('.frit/config'):
        fritutils.termout.printWarning("The '.frit/config file' already exists.")
    else:
        fritutils.termout.printSuccess("Creating '.frit/config'.")
        if not os.path.exists('.frit'):
            try:
                os.mkdir('.frit')
            except:
                fritutils.termout.printWarning("Cannot create .frit directory.")
                sys.exit(1)
        if not os.path.exists('.frit/logs'):
            try:
                os.mkdir('.frit/logs')
            except:
                fritutils.termout.printWarning("Cannot create .frit/logs directory.")
                sys.exit(1)
        try:
            fc=open('.frit/config','w')
            fc.write(CONFIG_TEMPLATE)
            fc.close()
        except:
            fritutils.termout.printWarning("Cannot write .frit/config file.")
            sys.exit(1)

