#!/usr/bin/python
import sys
import datetime
import os.path
import configobj
import argparse
import fritutils.termout
import fritcommands
import fritutils.fritlog
from fritutils import fritobjects


def checkInit(args):
    # check to see if .frit already exists
    if not fritutils.isCwdFrit():
        fritcommands.init.initCommand()
        sys.exit(0)
    else:
        fritutils.termout.printWarning("A .frit directory already exists.")
        sys.exit(1)

def mainFrit():
    # Check to see if a command was given.
    if len(sys.argv) < 2:
        fritutils.termout.printWarning('No command was given')
        sys.exit(1)
    # check to see if the current working dir is allowed
    fritutils.noBadPath()
    logger = fritutils.fritlog.loggers['mainfritLog']
    logger.info('Frit starting')
    parser = argparse.ArgumentParser(
            prog="frit",
            description='Forensic Robust Investigation Toolkit'
        )

    parser.add_argument(
        '-v',
        '--verbose',
        action='store_true',
        help='Verbose output.',
        default=False
        )

    parser.add_argument(
        '-d',
        '--debug',
        action='store_true',
        help='Debug messages in log files.',
        default=False
        )

    subparsers = parser.add_subparsers()

    init_parser = subparsers.add_parser(
            'init',
            help='Initialize frit before first usage.'
        )
    init_parser.set_defaults(func=checkInit,cmd='init')

    add_parser = subparsers.add_parser('add')
    add_parser.add_argument('files', nargs='+')
    add_parser.set_defaults(func=fritcommands.add.factory,cmd='add')

    args = parser.parse_args()
    if args.debug:
        fritutils.fritlog.setLevels('DEBUG')
    startTime = fritutils.startLog(args.cmd,logger)
    args.func(args)

    fritutils.stopLog(command, startTime, logger)
    sys.exit(0)

if __name__ == '__main__':
    mainFrit()
